language: java
jdk:
  - openjdk8

branched:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springBoot-project-simple *
  - mkdir -p deploy
  - mv springBoot-project-simple.zip deploy/sprinBoot-project-simple.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # travis repo settings 에 설정된 값
    bucket: springboot-project-simple # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy #before_deploy 에서 생성한 디렉토리 ( https://docs.travis-ci.com/user/deployment/s3/ )
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # travis repo settings 에 설정된 값
    bucket: springboot-project-simple # S3 버킷
    key: springBoot-project-simple.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springBoot-project-simple # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springBoot-project-simple-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - jgg0328@gmail.com