version: 0.0
os: linux
files:
  - source:  /  # CodeDeploy 에서 전달해준 파일 중 destination 으로 이동시킬 대상을 지정 ( / -> 전체 파일을 의미 )
    destination: /home/ubuntu/app/step3/zip/ # source 에서 지정된 파일을 받을 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ec2-user